
## BINDINGS

set -g prefix C-a


setw -g mode-keys vi
setw -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# Setup 'v' to begin selection as in Vim
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set -g status-style bg=colour17,fg=yellow,bright
set -g window-status-style bg=colour18,fg=white
set -g window-status-current-style bg=colour226,fg=blue,bright

set -g window-style 'bg=#444647'
set -g window-active-style 'bg=#1c1c1c'


bind C-c new-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'vitaly/tmux-pain-control'

run '~/.tmux/plugins/tpm/tpm'
