
## BINDINGS

set -g prefix C-a

setw -g mouse on

bind C-c new-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'vitaly/tmux-pain-control'

run '~/.tmux/plugins/tpm/tpm'
